# -*- coding: utf-8 -*-
"""ia2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rR-IU5ehdxvmYZCqEMdN6NgL5xcaiJio
"""

# Commented out IPython magic to ensure Python compatibility.

!apt-get update
!apt-get install -y openjdk-17-jdk wget unzip

!git clone https://github.com/kermitt2/grobid.git
# %cd grobid

!git checkout 0.8.2

!./gradlew clean install

import subprocess
import time

grobid_process = subprocess.Popen(['./gradlew', 'run'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
time.sleep(30)

from google.colab import files

print("Selecciona tus PDFs (máximo 10):")
uploaded = files.upload()
pdf_paths = list(uploaded.keys())
print("Archivos subidos:", pdf_paths)

import requests

xml_files = []

for pdf in pdf_paths:
    with open(pdf, 'rb') as f:
        response = requests.post("http://localhost:8070/api/processFulltextDocument", files={'input': f})

    xml_name = pdf.replace(".pdf", ".xml")
    with open(xml_name, "wb") as f:
        f.write(response.content)
    xml_files.append(xml_name)
from google.colab import files

for xml_file in xml_files:
    files.download(xml_file)
print("XML generados:", xml_files)